### ISSUE TITLE
Support for Arctis Nova 7

### ISSUE THREAD

**Issue by DaniDipp** [richrace/arctis-usb-finder#8]
I just got the Actis Nova 7 (released in August 2022) and would like to use this library to query their battery level. How can I help you find the magic numbers and add support for them?

**Comment by cyrilico** [comment]
Also interested in helping as I have the same model

**Comment by cyrilico** [comment]
@richrace I was able to run the script with some modifications (had to remove the check for `device.usage !== 1` and the Product ID for the Arctis Nova 7 is 8706 (0x2202)

**Comment by richrace** [comment]
Hi, just checking you had the USB dongle plugged in and could you update to the latest version of the package?

I don't have a bluetooth headset version to test with. Nor a Windows PC to test with.

**Comment by sqal** [comment]
Hi @@richrace  I wanted to use your [arctis-monitor](https://github.com/richrace/arctis-monitor) app but I found that it doesn't work with my Arctis Nova 7 headset. It shows me the message `No headphones found`. Then i found this issue and started digging into the source code. And as @cyrilico it seems that it does not find the device because this in `device.usage !== 1`  check in [gateway.ts#L21](https://github.com/richrace/arctis-usb-finder/blob/main/src/adapters/human_interface_device/gateway.ts#L21).  I added console.log in the filter and that's what I got

```
{
  vendorId: 4152,
  productId: 8706,
  path: '...',
  manufacturer: 'SteelSeries',
  product: 'Arctis Nova 7',
  release: 273,
  interface: 4,
  usagePage: 12,
  usage: 1
}
{
  vendorId: 4152,
  productId: 8706,
  path: '...',
  manufacturer: 'SteelSeries',
  product: 'Arctis Nova 7',
  release: 273,
  interface: 5,
  usagePage: 65280,
  usage: 1
}
{
  vendorId: 4152,
  productId: 8704,
  path: '...',
  manufacturer: 'SteelSeries',
  product: 'Arctis Nova 7',
  release: 275,
  interface: 0,
  usagePage: 65472,
  usage: 1
}
{
  vendorId: 4152,
  productId: 8706,
  path: '...',
  manufacturer: 'SteelSeries',
  product: 'Arctis Nova 7',
  release: 273,
  interface: 3,
  usagePage: 65472,
  usage: 1
}
{
  vendorId: 4152,
  productId: 8704,
  path: '...',
  manufacturer: 'SteelSeries',
  product: 'Arctis Nova 7',
  release: 275,
  interface: 1,
  usagePage: 12,
  usage: 1
}
```

**Comment by sqal** [comment]
Hi @richrace  I wanted to use your [arctis-monitor](https://github.com/richrace/arctis-monitor) app but I found that it doesn't work with my Arctis Nova 7 headset. It shows me the message `No headphones found`. Then i found this issue and started digging into the source code. And as @cyrilico it seems that it does not find the device because this  `device.usage !== 1`  check in [gateway.ts#L21](https://github.com/richrace/arctis-usb-finder/blob/main/src/adapters/human_interface_device/gateway.ts#L21).  I added console.log in the filter and that's what I got

```
{
  vendorId: 4152,
  productId: 8706,
  path: '...',
  manufacturer: 'SteelSeries',
  product: 'Arctis Nova 7',
  release: 273,
  interface: 4,
  usagePage: 12,
  usage: 1
}
{
  vendorId: 4152,
  productId: 8706,
  path: '...',
  manufacturer: 'SteelSeries',
  product: 'Arctis Nova 7',
  release: 273,
  interface: 5,
  usagePage: 65280,
  usage: 1
}
{
  vendorId: 4152,
  productId: 8704,
  path: '...',
  manufacturer: 'SteelSeries',
  product: 'Arctis Nova 7',
  release: 275,
  interface: 0,
  usagePage: 65472,
  usage: 1
}
{
  vendorId: 4152,
  productId: 8706,
  path: '...',
  manufacturer: 'SteelSeries',
  product: 'Arctis Nova 7',
  release: 273,
  interface: 3,
  usagePage: 65472,
  usage: 1
}
{
  vendorId: 4152,
  productId: 8704,
  path: '...',
  manufacturer: 'SteelSeries',
  product: 'Arctis Nova 7',
  release: 275,
  interface: 1,
  usagePage: 12,
  usage: 1
}
```

**Comment by richrace** [comment]
:eyes: Thanks for this, I'm currently rewriting this initial search.

**Comment by sqal** [comment]
Installed [v0.0.9](https://github.com/richrace/arctis-monitor/releases/tag/v0.0.9) but still have some issue. Now it says my headphones "are not connected". In the debug menu says "Found and possibly not configured" What does it mean? It's like this whether I have them connected with a USB-C cable or not.

![img](https://i.imgur.com/wDCqVJH.png)

**Comment by richrace** [comment]
I accidentally configured it wrong (hopefully) this release should work [v0.0.10](https://github.com/richrace/arctis-monitor/releases/tag/v0.0.10)

**Comment by sqal** [comment]
It seems to work now :) There are some minor visual bugs, like battery icon (emoji?) is rendered incorrectly or an invisible black handset icon in the tray but that's not very important right now. Anyway big thanks for making it work on Windows.  👍

![ss](https://i.imgur.com/gs7Rnxf.png)

**Comment by richrace** [comment]
I've fixed the emojis in the latest release https://github.com/richrace/arctis-monitor/releases/tag/v0.0.11
